version: '3.9'

services:
  dbi:
    image: ghcr.io/jbheuschen/dhbw-datenbanken-ii:latest
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=QXSb8RUvscYn3ZL9Gh4udq
    networks:
      - project
    depends_on:
      - redis
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379' # TODO remove
    hostname: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass QXSb8RUvscYn3ZL9Gh4udq
    volumes:
      - data:/data
    networks:
      - project
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
networks:
  project:
volumes:
  data:
  redis-insight:
